### ISSUE TITLE
Add CDDL

### ISSUE THREAD

**Issue by laurencelundblade** [ietf-rats-wg/draft-ietf-rats-uccs#4]
UCCS-message = UCCS-tagged-message / UCCS-untagged-message

UCCS-tagged-message = #6.601(cwt-claims-set)

UCCS-untagged-message = cwt-claims-set

Then where is cwt-claims-set defined? Seems like it would be OK to define it in the UCCS draft. Right now I define eat-claims-set in EAT and that includes some of the CWT claims. However, I'm OK for all that to move to UCCS. EAT needs a normative reference to UCCS anyway and it would be better to avoid a circular reference between EAT and UCCS.

https://github.com/ietf-rats-wg/eat/issues/130

**Comment by nedmsmith** [comment]
Is there something equivalent to cwt-claims-set defined for the payload of a CWT? Logically, a CWT is a 'signed-cwt-payload'. The unsigned part has to be recognizable as CBOR, so wouldn't that be the same as UCCS-untagged-message?

**Comment by laurencelundblade** [comment]
There is no CDDL definition of the payload of a CWT anywhere, no definition of cwt-claims-set anywhere.  It would be the same as UCCS-untagged-message which is why I thought it might be good to put it here.

It should also have a $$ CDDL socket that additional claims can be defined. EAT, for example woulds use the $$ CDDL socket for all it's claims.

**Comment by henkbirkholz** [comment]
[edited] Claims Sets are defined in RFC7519 and inherited by RFC8392. These Claims Sets are the basis for CWT and thereby are the "payload of a CWT". This might be just me, but I am drawing a blank here. Could you please provide a (preliminary) change proposal so that we can look at a potential solution to a problem statement that is hard for me to follow? At the moment, I am inclined to assume that this is an obvious non-issue - but again that might be me, not getting the problem.

**Comment by laurencelundblade** [comment]
Henk, they are defined in *prose*, but there is no accompanying CDDL as is becoming the convention for CBOR-based protocols.  There is no desire to redefine any semantics, just to add some CDDL that parallels what the prose says.

My immediate problem in EAT is that there's no CDDL to reference when a claim-set is to be used, not can I produce the top-level CDDL for EAT. To address this, I've constructed my own CDDL for a CWT and it is in EAT. That is tolerable, but it seems like it would be more general to have this in the more general UCCS.

Another problem is that there's no $$ socket to add claims to a CWT. All new CWT claims should probably be defined in CDDL. While a $$ socket is not required to define new claims in CDDL, it is helpful, particularly with the next.

A third problem is that EAT and other protocols (some of which are probably yours) are doing automated verification of the CDDL definition in the RFC against the examples in the RFC and more. If there's no CDDL, that can't be done.

My plan is to write up the cleanest CDDL I can that I think should go into UCCS. There's a less-clean version of it in EAT right now.  Then we can decide if it goes in EAT or more generally goes into UCCS.

**Comment by henkbirkholz** [comment]
Then let us define a CDDL specification in EAT instead of trying to use CDDL fragments as an information model, I'd say. I am rather certain that I brought this up before, but a few years ago that did not seem to be a viable route. If that has changed, we can create a feasible way forward - in the scope of EAT. Touching JWT and CWT to that seems a bit blown out of proportions, I think.

JWT and CWT are anchored in independent RFCs. If there would be enough support for reopening that work.. well I'd not be blocking that, but I'd also not be an advocate for that. I think I understand now, where you are coming from. But what you illustrate here as your target goes way beyond EAT. Maybe finishing EAT first should be the priority and then we can take the lessons learned and bring other folks in to talk about "Serialization Agnostics Claims Sets" and how these can be reused in JSON and/or CBOR?

**Comment by cabo** [comment]
I'm having a hard time following this discussion.

I think it is good to have CDDL for CWT (don't care about JWT).

I think it would be good to do this in a way that the act of registering new claims can be accompanied by adding simple CDDL for these claims.  So a including a socket seems like the right way to do this.

I don't think defining this CDDL warrants a CWTbis.  Writing a document specifically for this sounds a bit thin, but could be done (and would clearly be in the COSE WG). Attaching this to the UCCS document also works, certainly better than attaching it to some random CWT-using document (UCCS is "infrastructure" for CWT, EAT is not).

I'm not a big fan for doing everything with a ton of representation variants, so doing anything of this for JWT as well needs some good motivation (and maybe even resurrection of JOSE).

**Comment by henkbirkholz** [comment]
If we leave JWT out of the picture, this could boil down to provide "CWT CDDL" in the UCCS I-D? I can follow that thought. I never really had a problem with the English text definition in CWT, but admittedly most people seem to create "their own" CWT CDDL based on that English text anyways.

**Comment by cabo** [comment]
... yes, and having some easy-to-copy CDDL is preferable.

Also a common way to fill the socket.

I'll propose something later today.

**Comment by thomas-fossati** [comment]
I guess this conversation needs to be resurrected now that https://github.com/ietf-rats-wg/eat/pull/176 has landed.

**Comment by thomas-fossati** [comment]
@laurencelundblade is [this](https://github.com/ietf-rats-wg/eat/blob/master/cddl/external/uccs.cddl) the CDDL that should appear in UCCS?

PS: ideally, EAT-13 and UCCS-03 should come out at the same time.

**Comment by cabo** [comment]
Once https://github.com/ietf-rats-wg/eat/pull/336 is merged in the EAT document, we can close this issue.

**Comment by cabo** [comment]
Thanks, Laurence!
